TOP=../..
include $(TOP)/configure/CONFIG

DB += dg645.db
#DB += dg645Ch.db
DB += regens.db
DB += asynIO.db
DB_INSTALLS += $(ASYN)/db/asynRecord.db
#DB_INSTALLS += $(TIME)/db/timestamp.db

include $(TOP)/configure/RULES
